# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: mycluster.icp:8500/iwinoto/cardashboard
hpa:
  enabled: false
cloud_services:
  conversation:
    credentials: <Conversation service instance credentials JSON>
    workspace: <Conversation Workspace ID>
  speech_to_text:
    credentials: <Speech-to-Text service instance credentials JSON>
  text_to_speech:
    credentials: <Text-to-Speech service instance credentials JSON>
