language: node_js
dist: trusty
sudo: required
services:
  - docker

env:
  global:
  - CF_APP=car-dashboard
  - CF_API=https://api.au-syd.bluemix.net
  - CF_ORG=iwinoto@au1.ibm.com
  - CF_ACCOUNT=iwinoto@au1.ibm.com
  - CF_SPACE=bluemix-demo
  - REGISTRY=registry.au-syd.bluemix.net
  - REGISTRY_NAMESPACE=iwinoto_ibm
  - IMAGE_NAME=car-dashboard

before_install:
  - source install_bx.sh
  - bx login -a "$CF_API" -u "$CF_USERNAME" --apikey "$BMX_APIKEY" -o "$CF_ORG" -s "$CF_SPACE"
  - source k8s-setenv.sh

install: true

script:
  # Build Docker image to Bluemix container registry
  - docker build -t $REGISTRY/$REGISTRY_NAMESPACE/$IMAGE_NAME:1 .

after_success:
  - docker push $REGISTRY/$REGISTRY_NAMESPACE/$IMAGE_NAME:1

deploy:
  - source k8s-deploy.sh
