language: node_js
dist: trusty
sudo: required
services:
  - docker

script:
  # Build Docker image to Bluemix container registry
  - docker build -t $REGISTRY/$REGISTRY_NAMESPACE/$IMAGE_NAME:1 .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REGISTRY/$REGISTRY_NAMESPACE/$IMAGE_NAME:1
