language: node_js
dist: trusty
sudo: required
services:
  - docker

env:
  global:
  - CF_APP=car-dashboard
  - CF_API=https://api.au-syd.bluemix.net
  - CF_ORG=FunFactory
  - CF_SPACE=CC-Activation-Telstra

before_install:
  - source install_bx.sh
  - bx login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORG" -s "$CF_SPACE" -c "$CF_ACCOUNT"
  - bx cr login

install: true

script:
  # Build Docker image to Bluemix container registry
  - docker build -t $REGISTRY/$REGISTRY_NAMESPACE/$IMAGE_NAME:1 .

after_success:
  - docker push $REGISTRY/$REGISTRY_NAMESPACE/$IMAGE_NAME:1
